/*
@TargetNode='XOAP_Citrix_Director'
@GeneratedBy=s.sokolic
@GenerationDate=10/29/2022 10:55:23
@GenerationHost=DESKTOP-RQ1FOQF
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]Web-Server";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::9::9::WindowsFeature";
 Name = "Web-Server";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
ResourceID = "[WindowsFeature]Web-WebServer";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::15::9::WindowsFeature";
 Name = "Web-WebServer";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
ResourceID = "[WindowsFeature]Web-Common-Http";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::21::9::WindowsFeature";
 Name = "Web-Common-Http";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource4ref
{
ResourceID = "[WindowsFeature]Web-Default-Doc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::27::9::WindowsFeature";
 Name = "Web-Default-Doc";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource5ref
{
ResourceID = "[WindowsFeature]Web-Dir-Browsing";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::33::9::WindowsFeature";
 Name = "Web-Dir-Browsing";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource6ref
{
ResourceID = "[WindowsFeature]Web-Http-Errors";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::39::9::WindowsFeature";
 Name = "Web-Http-Errors";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource7ref
{
ResourceID = "[WindowsFeature]Web-Static-Content";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::45::9::WindowsFeature";
 Name = "Web-Static-Content";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource8ref
{
ResourceID = "[WindowsFeature]Web-Http-Redirect";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::51::9::WindowsFeature";
 Name = "Web-Http-Redirect";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource9ref
{
ResourceID = "[WindowsFeature]Web-Health";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::57::9::WindowsFeature";
 Name = "Web-Health";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource10ref
{
ResourceID = "[WindowsFeature]Web-Http-Logging";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::63::9::WindowsFeature";
 Name = "Web-Http-Logging";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource11ref
{
ResourceID = "[WindowsFeature]Web-Log-Libraries";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::69::9::WindowsFeature";
 Name = "Web-Log-Libraries";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource12ref
{
ResourceID = "[WindowsFeature]Web-Http-Tracing";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::75::9::WindowsFeature";
 Name = "Web-Http-Tracing";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource13ref
{
ResourceID = "[WindowsFeature]Web-Performance";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::81::9::WindowsFeature";
 Name = "Web-Performance";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource14ref
{
ResourceID = "[WindowsFeature]Web-Stat-Compression";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::87::9::WindowsFeature";
 Name = "Web-Stat-Compression";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource15ref
{
ResourceID = "[WindowsFeature]Web-Dyn-Compression";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::93::9::WindowsFeature";
 Name = "Web-Dyn-Compression";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource16ref
{
ResourceID = "[WindowsFeature]Web-Security";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::99::9::WindowsFeature";
 Name = "Web-Security";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource17ref
{
ResourceID = "[WindowsFeature]Web-Filtering";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::105::9::WindowsFeature";
 Name = "Web-Filtering";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource18ref
{
ResourceID = "[WindowsFeature]Web-Basic-Auth";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::111::9::WindowsFeature";
 Name = "Web-Basic-Auth";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource19ref
{
ResourceID = "[WindowsFeature]Web-Windows-Auth";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::117::9::WindowsFeature";
 Name = "Web-Windows-Auth";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource20ref
{
ResourceID = "[WindowsFeature]Web-App-Dev";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::123::9::WindowsFeature";
 Name = "Web-App-Dev";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource21ref
{
ResourceID = "[WindowsFeature]Web-Net-Ext45";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::129::9::WindowsFeature";
 Name = "Web-Net-Ext45";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource22ref
{
ResourceID = "[WindowsFeature]Web-ASP";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::135::9::WindowsFeature";
 Name = "Web-ASP";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource23ref
{
ResourceID = "[WindowsFeature]Web-Asp-Net45";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::141::9::WindowsFeature";
 Name = "Web-Asp-Net45";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource24ref
{
ResourceID = "[WindowsFeature]Web-CGI";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::147::9::WindowsFeature";
 Name = "Web-CGI";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource25ref
{
ResourceID = "[WindowsFeature]Web-ISAPI-Ext";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::153::9::WindowsFeature";
 Name = "Web-ISAPI-Ext";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource26ref
{
ResourceID = "[WindowsFeature]Web-ISAPI-Filter";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::159::9::WindowsFeature";
 Name = "Web-ISAPI-Filter";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource27ref
{
ResourceID = "[WindowsFeature]Web-Includes";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::165::9::WindowsFeature";
 Name = "Web-Includes";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource28ref
{
ResourceID = "[WindowsFeature]Web-Mgmt-Tools";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::171::9::WindowsFeature";
 Name = "Web-Mgmt-Tools";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource29ref
{
ResourceID = "[WindowsFeature]Web-Mgmt-Console";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::177::9::WindowsFeature";
 Name = "Web-Mgmt-Console";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource30ref
{
ResourceID = "[WindowsFeature]Web-Mgmt-Compat";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::183::9::WindowsFeature";
 Name = "Web-Mgmt-Compat";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource31ref
{
ResourceID = "[WindowsFeature]Web-Metabase";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::189::9::WindowsFeature";
 Name = "Web-Metabase";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource32ref
{
ResourceID = "[WindowsFeature]Web-Lgcy-Mgmt-Console";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::195::9::WindowsFeature";
 Name = "Web-Lgcy-Mgmt-Console";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource33ref
{
ResourceID = "[WindowsFeature]Web-Lgcy-Scripting";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::201::9::WindowsFeature";
 Name = "Web-Lgcy-Scripting";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource34ref
{
ResourceID = "[WindowsFeature]Web-WMI";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::207::9::WindowsFeature";
 Name = "Web-WMI";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource35ref
{
ResourceID = "[WindowsFeature]Web-Scripting-Tools";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::213::9::WindowsFeature";
 Name = "Web-Scripting-Tools";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource36ref
{
ResourceID = "[WindowsFeature]NET-Framework-45-ASPNET";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::219::9::WindowsFeature";
 Name = "NET-Framework-45-ASPNET";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource37ref
{
ResourceID = "[WindowsFeature]NET-WCF-HTTP-Activation45";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::225::9::WindowsFeature";
 Name = "NET-WCF-HTTP-Activation45";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource38ref
{
ResourceID = "[WindowsFeature]Remote-Assistance";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::231::9::WindowsFeature";
 Name = "Remote-Assistance";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource39ref
{
ResourceID = "[WindowsFeature]WAS";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::237::9::WindowsFeature";
 Name = "WAS";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource40ref
{
ResourceID = "[WindowsFeature]WAS-Process-Model";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::243::9::WindowsFeature";
 Name = "WAS-Process-Model";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of MSFT_RoleResource as $MSFT_RoleResource41ref
{
ResourceID = "[WindowsFeature]WAS-Config-APIs";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Director.ps1::249::9::WindowsFeature";
 Name = "WAS-Config-APIs";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Director";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="s.sokolic";

                        GenerationDate="10/29/2022 10:55:23";

                        GenerationHost="DESKTOP-RQ1FOQF";

                        Name="XOAP_Citrix_Director";

                    };
