/*
@TargetNode='XOAP_W11_2009_Citrix_Optimizer'
@GeneratedBy=s.sokolic
@GenerationDate=10/29/2022 13:59:34
@GenerationHost=DESKTOP-RQ1FOQF
*/

instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
ResourceID = "[Service]AJRouter";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::12::9::Service";
 Name = "AJRouter";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource2ref
{
ResourceID = "[Service]ALG";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::19::9::Service";
 Name = "ALG";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource3ref
{
ResourceID = "[Service]BthAvctpSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::26::9::Service";
 Name = "BthAvctpSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource4ref
{
ResourceID = "[Service]BDESVC";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::33::9::Service";
 Name = "BDESVC";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource5ref
{
ResourceID = "[Service]wbengine";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::40::9::Service";
 Name = "wbengine";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource6ref
{
ResourceID = "[Service]BTAGService";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::47::9::Service";
 Name = "BTAGService";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource7ref
{
ResourceID = "[Service]bthserv";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::54::9::Service";
 Name = "bthserv";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource8ref
{
ResourceID = "[Service]PeerDistSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::61::9::Service";
 Name = "PeerDistSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource9ref
{
ResourceID = "[Service]DusmSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::68::9::Service";
 Name = "DusmSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource10ref
{
ResourceID = "[Service]DPS";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::75::9::Service";
 Name = "DPS";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource11ref
{
ResourceID = "[Service]WdiServiceHost";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::82::9::Service";
 Name = "WdiServiceHost";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource12ref
{
ResourceID = "[Service]WdiSystemHost";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::89::9::Service";
 Name = "WdiSystemHost";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource13ref
{
ResourceID = "[Service]TrkWks";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::96::9::Service";
 Name = "TrkWks";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource14ref
{
ResourceID = "[Service]MapsBroker";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::103::9::Service";
 Name = "MapsBroker";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource15ref
{
ResourceID = "[Service]EFS";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::110::9::Service";
 Name = "EFS";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource16ref
{
ResourceID = "[Service]fdPHost";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::117::9::Service";
 Name = "fdPHost";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource17ref
{
ResourceID = "[Service]FDResPub";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::124::9::Service";
 Name = "FDResPub";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource18ref
{
ResourceID = "[Service]lfsvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::131::9::Service";
 Name = "lfsvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource19ref
{
ResourceID = "[Service]SharedAccess";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::138::9::Service";
 Name = "SharedAccess";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource20ref
{
ResourceID = "[Service]CscService";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::145::9::Service";
 Name = "CscService";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource21ref
{
ResourceID = "[Service]WpcMonSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::152::9::Service";
 Name = "WpcMonSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource22ref
{
ResourceID = "[Service]RetailDemo";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::159::9::Service";
 Name = "RetailDemo";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource23ref
{
ResourceID = "[Service]SensrSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::166::9::Service";
 Name = "SensrSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource24ref
{
ResourceID = "[Service]SSDPSRV";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::173::9::Service";
 Name = "SSDPSRV";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource25ref
{
ResourceID = "[Service]upnphost";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::180::9::Service";
 Name = "upnphost";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource26ref
{
ResourceID = "[Service]VacSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::187::9::Service";
 Name = "VacSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource27ref
{
ResourceID = "[Service]wcncsvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::194::9::Service";
 Name = "wcncsvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource28ref
{
ResourceID = "[Service]WMPNetworkSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::201::9::Service";
 Name = "WMPNetworkSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource29ref
{
ResourceID = "[Service]icssvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::208::9::Service";
 Name = "icssvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource30ref
{
ResourceID = "[Service]WlanSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::215::9::Service";
 Name = "WlanSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource31ref
{
ResourceID = "[Service]WwanSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::222::9::Service";
 Name = "WwanSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource32ref
{
ResourceID = "[Service]XboxGipSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::229::9::Service";
 Name = "XboxGipSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource33ref
{
ResourceID = "[Service]XblAuthManager";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::236::9::Service";
 Name = "XblAuthManager";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource34ref
{
ResourceID = "[Service]XblGameSave";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::243::9::Service";
 Name = "XblGameSave";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource35ref
{
ResourceID = "[Service]XboxNetApiSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::250::9::Service";
 Name = "XboxNetApiSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource36ref
{
ResourceID = "[Service]SysMain";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::257::9::Service";
 Name = "SysMain";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource37ref
{
ResourceID = "[Service]WerSvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::264::9::Service";
 Name = "WerSvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource38ref
{
ResourceID = "[Service]WSearch";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::271::9::Service";
 Name = "WSearch";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Disabled";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource39ref
{
ResourceID = "[Service]defragsvc";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::278::9::Service";
 Name = "defragsvc";
 State = "Stopped";
 ModuleName = "PsDesiredStateConfiguration";
 StartupType = "Manual";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage1ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.BingWeather_4.25.20211.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.BingWeather_4.25.20211.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::285::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage2ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.DesktopAppInstaller_2021.1207.634.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.DesktopAppInstaller_2021.1207.634.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::291::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage3ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.GetHelp_10.2111.43421.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.GetHelp_10.2111.43421.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::297::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage4ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.Getstarted_2021.2111.2.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.Getstarted_2021.2111.2.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::303::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage5ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.HEIFImageExtension_1.0.43012.0_x64__8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.HEIFImageExtension_1.0.43012.0_x64__8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::309::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage6ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.Microsoft3DViewer_2021.2107.7012.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.Microsoft3DViewer_2021.2107.7012.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::315::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage7ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.MicrosoftOfficeHub_18.2110.13110.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.MicrosoftOfficeHub_18.2110.13110.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::321::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage8ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.MicrosoftSolitaireCollection_4.12.1050.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.MicrosoftSolitaireCollection_4.12.1050.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::327::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage9ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.MicrosoftStickyNotes_4.2.2.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.MicrosoftStickyNotes_4.2.2.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::333::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage10ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.MixedReality.Portal_2000.21051.1282.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.MixedReality.Portal_2000.21051.1282.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::339::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage11ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.MSPaint_2021.2105.4017.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.MSPaint_2021.2105.4017.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::345::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage12ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.Office.OneNote_16001.14326.20674.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.Office.OneNote_16001.14326.20674.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::351::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage13ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.People_2021.2105.4.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.People_2021.2105.4.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::357::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage14ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.ScreenSketch_2020.814.2355.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.ScreenSketch_2020.814.2355.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::363::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage15ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.SkypeApp_15.79.95.0_neutral_~_kzf8qxf38zg5c";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.SkypeApp_15.79.95.0_neutral_~_kzf8qxf38zg5c";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::369::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage16ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.StorePurchaseApp_12109.1001.10.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.StorePurchaseApp_12109.1001.10.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::375::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage17ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.VP9VideoExtensions_1.0.42791.0_x64__8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.VP9VideoExtensions_1.0.42791.0_x64__8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::381::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage18ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.Wallet_2.4.18324.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.Wallet_2.4.18324.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::387::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage19ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WebMediaExtensions_1.0.42192.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WebMediaExtensions_1.0.42192.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::393::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage20ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WebpImageExtension_1.0.42351.0_x64__8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WebpImageExtension_1.0.42351.0_x64__8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::399::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage21ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.Windows.Photos_2021.21090.10008.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.Windows.Photos_2021.21090.10008.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::405::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage22ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsAlarms_2021.2101.28.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsAlarms_2021.2101.28.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::411::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage23ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsCalculator_2020.2103.8.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsCalculator_2020.2103.8.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::417::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage24ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsCamera_2021.105.10.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsCamera_2021.105.10.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::423::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage25ref
{
ModuleVersion = "0.1.0";
 PackageName = "microsoft.windowscommunicationsapps_16005.14326.20544.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]microsoft.windowscommunicationsapps_16005.14326.20544.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::429::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage26ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsFeedbackHub_2022.106.2230.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsFeedbackHub_2022.106.2230.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::435::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage27ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsMaps_2021.2104.2.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsMaps_2021.2104.2.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::441::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage28ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsSoundRecorder_2021.2103.28.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsSoundRecorder_2021.2103.28.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::447::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage29ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.WindowsStore_22112.1401.2.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.WindowsStore_22112.1401.2.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::453::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage30ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.Xbox.TCUI_1.24.10001.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.Xbox.TCUI_1.24.10001.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::459::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage31ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.XboxApp_48.78.15001.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.XboxApp_48.78.15001.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::465::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage32ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.XboxGameOverlay_1.54.4001.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.XboxGameOverlay_1.54.4001.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::471::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage33ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.XboxGamingOverlay_5.721.12013.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.XboxGamingOverlay_5.721.12013.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::477::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage34ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.XboxIdentityProvider_12.83.12001.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.XboxIdentityProvider_12.83.12001.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::483::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage35ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::489::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage36ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.YourPhone_1.21121.250.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.YourPhone_1.21121.250.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::495::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage37ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.ZuneMusic_2019.21102.11411.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.ZuneMusic_2019.21102.11411.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::501::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of cAppxProvisionedPackage as $cAppxProvisionedPackage38ref
{
ModuleVersion = "0.1.0";
 PackageName = "Microsoft.ZuneVideo_2019.21111.10511.0_neutral_~_8wekyb3d8bbwe";
 ResourceID = "[cAppxProvisionedPackage]Microsoft.ZuneVideo_2019.21111.10511.0_neutral_~_8wekyb3d8bbwe";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::507::9::cAppxProvisionedPackage";
 Ensure = "Absent";
 ModuleName = "XOAPAppxPackageDSC";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask1ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]AnalyzeSystem";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::513::9::ScheduledTask";
 Enable = False;
 TaskName = "AnalyzeSystem";
 TaskPath = "\\Microsoft\\Windows\\Power Efficiency Diagnostics";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask2ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]BfeOnServiceStartTypeChange";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::521::9::ScheduledTask";
 Enable = False;
 TaskName = "BfeOnServiceStartTypeChange";
 TaskPath = "\\Microsoft\\Windows\\Windows Filtering Platform";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask3ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Cellular";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::529::9::ScheduledTask";
 Enable = False;
 TaskName = "Cellular";
 TaskPath = "\\Microsoft\\Windows\\Management\\Provisioning\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask4ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Consolidator";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::537::9::ScheduledTask";
 Enable = False;
 TaskName = "Consolidator";
 TaskPath = "\\Microsoft\\Windows\\Customer Experience Improvement Program";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask5ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Diagnostics";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::545::9::ScheduledTask";
 Enable = False;
 TaskName = "Diagnostics";
 TaskPath = "\\Microsoft\\Windows\\DiskFootprint\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask6ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]FamilySafetyMonitor";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::553::9::ScheduledTask";
 Enable = False;
 TaskName = "FamilySafetyMonitor";
 TaskPath = "\\Microsoft\\Windows\\Shell";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask7ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]FamilySafetyRefreshTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::561::9::ScheduledTask";
 Enable = False;
 TaskName = "FamilySafetyRefreshTask";
 TaskPath = "\\Microsoft\\Windows\\Shell";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask8ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]File History (maintenance mode)";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::569::9::ScheduledTask";
 Enable = False;
 TaskName = "File History (maintenance mode)";
 TaskPath = "\\Microsoft\\Windows\\FileHistory";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask9ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]WindowsActionDialog";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::577::9::ScheduledTask";
 Enable = False;
 TaskName = "WindowsActionDialog";
 TaskPath = "\\Microsoft\\Windows\\Location";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask10ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Notifications";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::585::9::ScheduledTask";
 Enable = False;
 TaskName = "Notifications";
 TaskPath = "\\Microsoft\\Windows\\Location";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask11ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]MapsToastTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::593::9::ScheduledTask";
 Enable = False;
 TaskName = "MapsToastTask";
 TaskPath = "\\Microsoft\\Windows\\Maps";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask12ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]MapsUpdateTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::601::9::ScheduledTask";
 Enable = False;
 TaskName = "MapsUpdateTask";
 TaskPath = "\\Microsoft\\Windows\\Maps";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask13ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Microsoft Compatibility Appraiser";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::609::9::ScheduledTask";
 Enable = False;
 TaskName = "Microsoft Compatibility Appraiser";
 TaskPath = "\\Microsoft\\Windows\\Application Experience";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask14ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Microsoft-Windows-DiskDiagnosticDataCollector";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::617::9::ScheduledTask";
 Enable = False;
 TaskName = "Microsoft-Windows-DiskDiagnosticDataCollector";
 TaskPath = "\\Microsoft\\Windows\\DiskDiagnostic";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask15ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Microsoft-Windows-DiskDiagnosticResolver";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::625::9::ScheduledTask";
 Enable = False;
 TaskName = "Microsoft-Windows-DiskDiagnosticResolver";
 TaskPath = "\\Microsoft\\Windows\\DiskDiagnostic";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask16ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]MNO Metadata Parser";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::633::9::ScheduledTask";
 Enable = False;
 TaskName = "MNO Metadata Parser";
 TaskPath = "\\Microsoft\\Windows\\Mobile Broadband Accounts";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask17ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]NotificationTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::641::9::ScheduledTask";
 Enable = False;
 TaskName = "NotificationTask";
 TaskPath = "\\Microsoft\\Windows\\WwanSvc\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask18ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ProactiveScan";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::649::9::ScheduledTask";
 Enable = False;
 TaskName = "ProactiveScan";
 TaskPath = "\\Microsoft\\Windows\\CHKDSK";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask19ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ProcessMemoryDiagnosticEvents";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::657::9::ScheduledTask";
 Enable = False;
 TaskName = "ProcessMemoryDiagnosticEvents";
 TaskPath = "\\Microsoft\\Windows\\MemoryDiagnostic";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask20ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ProgramDataUpdater";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::665::9::ScheduledTask";
 Enable = False;
 TaskName = "ProgramDataUpdater";
 TaskPath = "\\Microsoft\\Windows\\Application Experience";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask21ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Proxy";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::673::9::ScheduledTask";
 Enable = False;
 TaskName = "Proxy";
 TaskPath = "\\Microsoft\\Windows\\Autochk";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask22ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]RecommendedTroubleshootingScanner";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::681::9::ScheduledTask";
 Enable = False;
 TaskName = "RecommendedTroubleshootingScanner";
 TaskPath = "\\Microsoft\\Windows\\Diagnosis\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask23ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ReconcileFeatures";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::689::9::ScheduledTask";
 Enable = False;
 TaskName = "ReconcileFeatures";
 TaskPath = "\\Microsoft\\Windows\\Flighting\\FeatureConfig\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask24ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ReconcileLanguageResources";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::697::9::ScheduledTask";
 Enable = False;
 TaskName = "ReconcileLanguageResources";
 TaskPath = "\\Microsoft\\Windows\\LanguageComponentsInstaller\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask25ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]RefreshCache";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::705::9::ScheduledTask";
 Enable = False;
 TaskName = "RefreshCache";
 TaskPath = "\\Microsoft\\Windows\\Flighting\\OneSettings\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask26ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]RegIdleBackup";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::713::9::ScheduledTask";
 Enable = False;
 TaskName = "RegIdleBackup";
 TaskPath = "\\Microsoft\\Windows\\Registry";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask27ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ResolutionHost";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::721::9::ScheduledTask";
 Enable = False;
 TaskName = "ResolutionHost";
 TaskPath = "\\Microsoft\\Windows\\WDI";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask28ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ResPriStaticDbSync";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::729::9::ScheduledTask";
 Enable = False;
 TaskName = "ResPriStaticDbSync";
 TaskPath = "\\Microsoft\\Windows\\Sysmain\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask29ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]RunFullMemoryDiagnostic";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::737::9::ScheduledTask";
 Enable = False;
 TaskName = "RunFullMemoryDiagnostic";
 TaskPath = "\\Microsoft\\Windows\\MemoryDiagnostic";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask30ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ScanForUpdates";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::745::9::ScheduledTask";
 Enable = False;
 TaskName = "ScanForUpdates";
 TaskPath = "\\Microsoft\\Windows\\InstallService\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask31ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ScanForUpdatesAsUser";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::753::9::ScheduledTask";
 Enable = False;
 TaskName = "ScanForUpdatesAsUser";
 TaskPath = "\\Microsoft\\Windows\\InstallService\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask32ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Scheduled";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::762::9::ScheduledTask";
 Enable = False;
 TaskName = "Scheduled";
 TaskPath = "\\Microsoft\\Windows\\Diagnosis";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask33ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]ScheduledDefrag";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::770::9::ScheduledTask";
 Enable = False;
 TaskName = "ScheduledDefrag";
 TaskPath = "\\Microsoft\\Windows\\Defrag";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask34ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]SilentCleanup";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::778::9::ScheduledTask";
 Enable = False;
 TaskName = "SilentCleanup";
 TaskPath = "\\Microsoft\\Windows\\DiskCleanup\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask35ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]SmartRetry";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::786::9::ScheduledTask";
 Enable = False;
 TaskName = "SmartRetry";
 TaskPath = "\\Microsoft\\Windows\\InstallService\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask36ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]SpaceAgentTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::794::9::ScheduledTask";
 Enable = False;
 TaskName = "SpaceAgentTask";
 TaskPath = "\\Microsoft\\Windows\\SpacePort\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask37ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]SpaceManagerTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::802::9::ScheduledTask";
 Enable = False;
 TaskName = "SpaceManagerTask";
 TaskPath = "\\Microsoft\\Windows\\SpacePort\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask38ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]SpeechModelDownloadTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::810::9::ScheduledTask";
 Enable = False;
 TaskName = "SpeechModelDownloadTask";
 TaskPath = "\\Microsoft\\Windows\\Speech\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask39ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Sqm-Tasks";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::818::9::ScheduledTask";
 Enable = False;
 TaskName = "Sqm-Tasks";
 TaskPath = "\\Microsoft\\Windows\\PI\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask40ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]SR";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::826::9::ScheduledTask";
 Enable = False;
 TaskName = "SR";
 TaskPath = "\\Microsoft\\Windows\\SystemRestore";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask41ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]StartComponentCleanup";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::834::9::ScheduledTask";
 Enable = False;
 TaskName = "StartComponentCleanup";
 TaskPath = "\\Microsoft\\Windows\\Servicing";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask42ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]StartupAppTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::842::9::ScheduledTask";
 Enable = False;
 TaskName = "StartupAppTask";
 TaskPath = "\\Microsoft\\Windows\\Application Experience";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask43ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]StorageSense";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::850::9::ScheduledTask";
 Enable = False;
 TaskName = "StorageSense";
 TaskPath = "\\Microsoft\\Windows\\DiskFootprint\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask44ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]UninstallDeviceTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::858::9::ScheduledTask";
 Enable = False;
 TaskName = "UninstallDeviceTask";
 TaskPath = "\\Microsoft\\Windows\\Bluetooth\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask45ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]UsbCeip";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::866::9::ScheduledTask";
 Enable = False;
 TaskName = "UsbCeip";
 TaskPath = "\\Microsoft\\Windows\\Customer Experience Improvement Program";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask46ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]Usb-Notifications";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::874::9::ScheduledTask";
 Enable = False;
 TaskName = "Usb-Notifications";
 TaskPath = "\\Microsoft\\Windows\\USB\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask47ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]VerifyWinRE";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::882::9::ScheduledTask";
 Enable = False;
 TaskName = "VerifyWinRE";
 TaskPath = "\\Microsoft\\Windows\\RecoveryEnvironment";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask48ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]WIM-Hash-Management";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::890::9::ScheduledTask";
 Enable = False;
 TaskName = "WIM-Hash-Management";
 TaskPath = "\\Microsoft\\Windows\\WOF\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask49ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]QueueReporting";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::898::9::ScheduledTask";
 Enable = False;
 TaskName = "QueueReporting";
 TaskPath = "\\Microsoft\\Windows\\Windows Error Reporting";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask50ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]UpdateLibrary";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::906::9::ScheduledTask";
 Enable = False;
 TaskName = "UpdateLibrary";
 TaskPath = "\\Microsoft\\Windows\\Windows Media Sharing";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask51ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]WinSAT";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::914::9::ScheduledTask";
 Enable = False;
 TaskName = "WinSAT";
 TaskPath = "\\Microsoft\\Windows\\Maintenance";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask52ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]WsSwapAssessmentTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::922::9::ScheduledTask";
 Enable = False;
 TaskName = "WsSwapAssessmentTask";
 TaskPath = "\\Microsoft\\Windows\\Sysmain\\";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of DSC_ScheduledTask as $DSC_ScheduledTask53ref
{
ModuleVersion = "8.5.0";
 ResourceID = "[ScheduledTask]XblGameSaveTask";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::930::9::ScheduledTask";
 Enable = False;
 TaskName = "XblGameSaveTask";
 TaskPath = "\\Microsoft\\XblGameSave";
 Ensure = "Absent";
 ModuleName = "ComputerManagementDsc";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
ResourceID = "[Registry]DeleteUserAppContainersOnLogoff";
 Key = "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::938::9::Registry";
 ValueName = "DeleteUserAppContainersOnLogoff";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "1"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource2ref
{
ResourceID = "[Registry]EnableAutoLayout";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\OptimalLayout";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::947::9::Registry";
 ValueName = "EnableAutoLayout";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource3ref
{
ResourceID = "[Registry]Enable";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Dfrg\\BootOptimizeFunction";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::956::9::Registry";
 ValueName = "Enable";
 ValueType = "String";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "N"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource4ref
{
ResourceID = "[Registry]ScreenSaveActive";
 Key = "HKEY_USERS\\.DEFAULT\\Control Panel\\Desktop";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::965::9::Registry";
 ValueName = "ScreenSaveActive";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource5ref
{
ResourceID = "[Registry]HibernateEnabled";
 Key = "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Power";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::974::9::Registry";
 ValueName = "HibernateEnabled";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource6ref
{
ResourceID = "[Registry]CrashDumpEnabled";
 Key = "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\CrashControl";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::983::9::Registry";
 ValueName = "CrashDumpEnabled";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource7ref
{
ResourceID = "[Registry]AllowStorageSenseGlobal";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\StorageSense";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::992::9::Registry";
 ValueName = "AllowStorageSenseGlobal";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource8ref
{
ResourceID = "[Registry]EnableFirstLogonAnimation";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::1001::9::Registry";
 ValueName = "EnableFirstLogonAnimation";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource9ref
{
ResourceID = "[Registry]ErrorMode";
 Key = "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Windows";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::1010::9::Registry";
 ValueName = "ErrorMode";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "2"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource10ref
{
ResourceID = "[Registry]AllowCortana";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::1019::9::Registry";
 ValueName = "AllowCortana";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource11ref
{
ResourceID = "[Registry]NoAutoUpdate";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::1028::9::Registry";
 ValueName = "NoAutoUpdate";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "1"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource12ref
{
ResourceID = "[Registry]CEIPEnable";
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\SQMClient\\Windows";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\optimizer\\XOAP_W11_2009_Citrix_Optimizer.ps1::1037::9::Registry";
 ValueName = "CEIPEnable";
 ValueType = "Dword";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";
 ValueData = {
    "0"
};

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_W11_2009_Citrix_Optimizer";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="s.sokolic";

                        GenerationDate="10/29/2022 13:59:34";

                        GenerationHost="DESKTOP-RQ1FOQF";

                        Name="XOAP_W11_2009_Citrix_Optimizer";

                    };
