/*
@TargetNode='XOAP_Citrix_Virtual_Delivery_Agent'
@GeneratedBy=s.sokolic
@GenerationDate=10/29/2022 11:52:29
@GenerationHost=DESKTOP-RQ1FOQF
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]Remote-Desktop-Services";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Virtual_Delivery_Agent.ps1::9::9::WindowsFeature";
 Name = "Remote-Desktop-Services";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Virtual_Delivery_Agent";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
ResourceID = "[WindowsFeature]RDS-RD-Server";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Virtual_Delivery_Agent.ps1::15::9::WindowsFeature";
 Name = "RDS-RD-Server";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Virtual_Delivery_Agent";
};
instance of MSFT_RoleResource as $MSFT_RoleResource3ref
{
ResourceID = "[WindowsFeature]Server-Media-Foundation";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Virtual_Delivery_Agent.ps1::21::9::WindowsFeature";
 Name = "Server-Media-Foundation";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Virtual_Delivery_Agent";
};
instance of MSFT_RoleResource as $MSFT_RoleResource4ref
{
ResourceID = "[WindowsFeature]Remote-Assistance";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Virtual_Delivery_Agent.ps1::27::9::WindowsFeature";
 Name = "Remote-Assistance";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Virtual_Delivery_Agent";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="s.sokolic";

                        GenerationDate="10/29/2022 11:52:29";

                        GenerationHost="DESKTOP-RQ1FOQF";

                        Name="XOAP_Citrix_Virtual_Delivery_Agent";

                    };
