/*
@TargetNode='Configure_Firewall'
@GeneratedBy=s.sokolic
@GenerationDate=10/29/2022 10:59:11
@GenerationHost=DESKTOP-RQ1FOQF
*/

instance of DSC_Firewall as $DSC_Firewall1ref
{
ModuleVersion = "9.0.0";
 ResourceID = "[Firewall]EnableBuiltInFirewallRule";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\server\\Configure_Firewall.ps1::8::9::Firewall";
 Enabled = "True";
 Name = "IIS-WebServerRole-HTTP-In-TCP";
 Ensure = "Present";
 ModuleName = "NetworkingDsc";
 ConfigurationName = "Configure_Firewall";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="s.sokolic";

                        GenerationDate="10/29/2022 10:59:11";

                        GenerationHost="DESKTOP-RQ1FOQF";

                        Name="Configure_Firewall";

                    };
