/*
@TargetNode='XOAP_Citrix_Universal_Print_Server'
@GeneratedBy=s.sokolic
@GenerationDate=10/29/2022 11:51:09
@GenerationHost=DESKTOP-RQ1FOQF
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]Print-Services";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Universal_Print_Server.ps1::9::9::WindowsFeature";
 Name = "Print-Services";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Universal_Print_Server";
};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
ResourceID = "[WindowsFeature]Print-Server";
 SourceInfo = "D:\\SynologyDrive\\_WIP\\xoap-powershell-dsc-configurations\\citrix\\XOAP_Citrix_Universal_Print_Server.ps1::15::9::WindowsFeature";
 Name = "Print-Server";
 Ensure = "Present";
 ModuleName = "PsDesiredStateConfiguration";

ModuleVersion = "1.0";
 ConfigurationName = "XOAP_Citrix_Universal_Print_Server";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="s.sokolic";

                        GenerationDate="10/29/2022 11:51:09";

                        GenerationHost="DESKTOP-RQ1FOQF";

                        Name="XOAP_Citrix_Universal_Print_Server";

                    };
