Install-Module -Name AccessControlDSC -Force
Install-Module -Name ActiveDirectoryDsc -Force
Install-Module -Name AdfsDsc -Force
Install-Module -Name AuditPolicyDsc -Force
Install-Module -Name AuditSystemDsc -Force
Install-Module -Name AzureWvdDsc -Force
Install-Module -Name cChocoEx -Force
Install-Module -Name cDockerDSC -Force
Install-Module -Name cElasticSearchDSC -Force
Install-Module -Name CertificateDsc -Force
Install-Module -Name CISDSC -Force
Install-Module -Name CitrixPVS -Force
Install-Module -Name cNtfsAccessControl -Force
Install-Module -Name ComputerManagementDsc -Force
Install-Module -Name ConfigMgrCBDsc -Force
Install-Module -Name DSCR_Shortcut -Force
Install-Module -Name DFSDsc -Force
Install-Module -Name DnsServerDsc -Force
Install-Module -Name DSCR_FileContent -Force
Install-Module -Name DSCR_AutoLogon -Force
Install-Module -Name DSCR_Shortcut -Force
Install-Module -Name DSCR_Application -Force
Install-Module -Name DSCR_PowerPlan -Force
Install-Module -Name DSCR_MSLicense -Force
Install-Module -Name DSCR_Font -Force
Install-Module -Name DSCR_AppxPackage -Force
Install-Module -Name FileSystemDsc -Force
Install-Module -Name FSRMDsc -Force
Install-Module -Name GPRegistryPolicyDsc -Force
Install-Module -Name JeaDsc -Force
Install-Module -Name LanguageDsc -Force
Install-Module -Name Microsoft365DSC -Force
Install-Module -Name NetworkingDsc -Force
Install-Module -Name OneDriveDsc -Force
Install-Module -Name PendingReboot -Force
Install-Module -Name PolicyFileEditor -Force
Install-Module -Name PowerShellModule -Force
Install-Module -Name PSDscResources -Force
Install-Module -Name SChannelDsc -Force
Install-Module -Name SecurityPolicyDsc -Force
Install-Module -Name SharePointDSC -Force
Install-Module -Name SqlServerDsc -Force
Install-Module -Name StorageDsc -Force
Install-Module -Name SystemLocaleDsc -Force
Install-Module -Name UpdateServicesDsc -Force
Install-Module -Name VMware.vSphereDSC -Force
Install-Module -Name WindowsDefenderDsc -Force
Install-Module -Name WSManDsc -Force
Install-Module -Name xActiveDirectory -Force
Install-Module -Name xAdcsDeployment -Force
Install-Module -Name xBitlocker -Force
Install-Module -Name xCertificate -Force
Install-Module -Name xCredSSP -Force
Install-Module -Name xDhcpServer -Force
Install-Module -Name xDnsServer -Force
Install-Module -Name XenDesktop7 -Force
Install-Module -Name xExchange -Force
Install-Module -Name xFailOverCluster -Force
Install-Module -Name xHyper-V -Force
Install-Module -Name xNetworking -Force
Install-Module -Name xPrinterManagement -Force
Install-Module -Name xPSDesiredStateConfiguration -Force
Install-Module -Name xRemoteDesktopSessionHost -Force
Install-Module -Name xSmbShare -Force
Install-Module -Name xStorage -Force
Install-Module -Name xSystemSecurity -Force
Install-Module -Name xWebAdministration -Force
